[project]
name = "src"
version = "0.0.1"
description = "This is my first project on MLOPS"
authors = [{name = "Samrat Roychoudhury", email = "samrat.rc47@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}