columns: 
  - _id: int
  - Pregnancies: int
  - Glucose: int
  - BloodPressure: int
  - SkinThickness: int
  - Insulin: int
  - BMI: float
  - DiabetesPedigreeFunction: float
  - Age: int
  - Outcome: int

numerical_columns:
  - _id
  - Pregnancies
  - BloodPressure
  - SkinThickness
  - DiabetesPedigreeFunction
  - Age
  - Outcome

categorical_columns:
  - BMI
  - Insulin
  - Glucose

drop_columns: _id


# for data transformation
robust_columns:
  - Pregnancies
  - BloodPressure
  - SkinThickness
  - DiabetesPedigreeFunction
  - Age
  - BMI
  - Insulin
  - Glucose

std_columns:
  - Pregnancies
  - BloodPressure
  - SkinThickness
  - DiabetesPedigreeFunction
  - Age
  - BMI
  - Insulin
  - Glucose
  - NewBMI_Obesity 1
  - NewBMI_Obesity 2 
  - NewBMI_Obesity 3
  - NewBMI_Overweight
  - NewBMI_Underweight
  - NewInsulinScore_Normal
  - NewGlucose_Low
  - NewGlucose_Normal
  - NewGlucose_Overweight
  - NewGlucose_Secret

columns_to_replace_zeros:
  - Pregnancies
  - Glucose
  - BloodPressure
  - SkinThickness
  - Insulin
  - BMI
  - DiabetesPedigreeFunction
  - Age

